### ISSUE TITLE
Seems like a icon is missing

### ISSUE THREAD

**Issue by gj1118** [charkour/react-reactions#120]
**Describe the bug**
It seems that the icons are not getting rendered. I ran the examples and I am seeing this 
![image](https://user-images.githubusercontent.com/473101/149602822-1f1038c5-6090-44f7-954e-6d3cf78a4890.png)
In my app as well, I am seeing this icon instead of the usual "smiley" icon .. Is this expected?
![image](https://user-images.githubusercontent.com/473101/149602885-b81c373f-e194-4b86-823c-dbad45170691.png)

**To Reproduce**
1. Install the package
2. Import as such `import { SlackCounter } from "@charkour/react-reactions";`
3. Use as such ` <SlackCounter />`
4. You will observe that there are rectangles all over instead of the icons

**Expected behavior**
An icon should appear where the user needs to click. RIght now a rectangle appears.

**Desktop (please complete the following information):**
 - OS: MacOs 12.0.1
 - Browser Chrome (97.0)

**Comment by gj1118** [comment]
Apologies this was my bad. I have got it working. 

Apologies for the spam.

**Comment by charkour** [comment]
All good. Glad is it working!

**Comment by michaelshum** [comment]
@gj1118 How did you resolve this? I tried downloading the required fonts into public/, but for any sub-pages I get a `GET http://localhost:3000/places/fonts/slack-icons-Regular.woff net::ERR_ABORTED 404 (Not Found)`, since the page is fetching from the subdir... what's the right way to handle the fonts?
